version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  celery:
    build: .
    command: celery -A personal_yt_api worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A personal_yt_api beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis