# Generated by Django 3.2.6 on 2021-08-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField(max_length=5000)),
                ('channel_title', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('thumbnail_url', models.URLField()),
            ],
            options={
                'verbose_name': 'YouTube Video',
                'verbose_name_plural': 'YouTube Videos',
            },
        ),
    ]
