# Generated by Django 3.2.6 on 2021-08-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='video_url',
            field=models.URLField(default='hello'),
            preserve_default=False,
        ),
    ]
